### ISSUE TITLE
typo found

### ISSUE THREAD

**Issue by pateketrueke** [rixo/svench#19]
I'm not sure by this line seems bit wrong?

https://github.com/rixo/svench/blob/master/lib/preprocessor.js#L74

**Comment by rixo** [comment]
Hmm... Nothing obvious to me. Why?

**Comment by pateketrueke** [comment]
> Have you encountered an actual problem pertaining to that? 

not really, I just was reading the code and found `Litteral` with the double t, is that expected? Just by curiousity.

**Comment by rixo** [comment]
Yeah, this is a mistake. Will fix. Thanks for taking the time to report.

Rereading the code, it should break something like this:

```svelte
<svench:options title={"title"} />
```

Svench options needs to be statically analyzable because they're parsed at compile time, and the above is static enough so it should be accepted. But I think the error you've found would make it to be rejected. I will confirm by testing and fix it when I get some calm :sweat_smile:

**Comment by rixo** [comment]
Will be fixed soon: https://github.com/rixo/svench/commit/aa8e4bce09212795d0fd4e8f1444e81b3848a289

Have you found any other interesting things while looking around?

**Comment by rixo** [comment]
This has been published on the v0.2.0-x beta branch.
