### ISSUE TITLE
Error: Cannot find module 'rollup-plugin-svelte-hot'

### ISSUE THREAD

**Issue by radu-m** [rixo/svench#24]
![image](https://user-images.githubusercontent.com/1469071/106063476-cd8ca780-612a-11eb-8878-e9f71bbb2888.png)

Don't have time right now, but if I figure it out these days, I'll post a resolution

**Comment by rixo** [comment]
Hey! Thanks for reporting.

This is because the example was using `svench@next`, but it was incorrect in `package.json`. This should be fixed now, can you retry?

Sorry for the mess inside the demo ... It's been more of a note keeper than actual demo for now :sweat_smile:

I still recommend using the component template, for now, if you intend to use it.

**Comment by rixo** [comment]
Or are you trying to build Svench itself? In this case, you should try the `next` branch, it is way ahead of master... Tip of dev is even the `snowpack` branch, but I'm not sure how stable is the last things I've pushed on it.

**Comment by rixo** [comment]
`main` branch (replaced `master`) has been updated with the last code we have. Currently in beta, and document in progress, but you should be able to play with the code if that's still your intention. So closing this now. Feel free to reopen if you still have the problem or some follow up question.
